var wikipedia = {
  paragraphs: [
    {data: '<p>"I remember my first right turn!"</p>'},
    {data: '<p>June 22nd: Bright sun, cold breeze. A picnic on the hill with vegan cheese and coffee cake.</p>'},
    {data: '<p>Grapefruit mules and dancing at Spirit.</p>'},
    {data: '<p>June 9th: Cat reading Mattia\'s tarot cards: "Big Chariot Energy"</p>'},
    {data: '<p>Kissing with a view of Pittsburgh</p>'},
    {data: '<p>Mattia kept quoting movies Cat had never seen before.</p>'},
    {data: '<p>Getting high and watching the Big Lebowski</p>'},
    {data: '<p>"I remember my first road rage!"</p>'},
    {data: '<p>June 6th: Cat and Mattia meet for the first time over coffee at Commonplace and ice from Rita\'s. Mattia talks a lot and Cat listens. She messages her friend that Mattia is cute, and she feels safe.</p>'},
    {data: '<p>June 9th: Mattia reading Cat\'s tarot cards: "A gourd (success), but at what cost??"</p>'},
    {data: '<p>June 11th: Mattia texts Cat: <br>"The woods are lovely and dark and deep,<br>and I have promises to keep,<br> and I have miles to go before I sleep. <br><b>Did you hear me butterfly? Miles to go before you sleep</b>"</p>'},
    {data: '<p>Cat reading Mattia\'s new Moon tarot cards: "Become a firefly, your own source of light. There is beauty and meaning in your pain."</p>'},
    {data: '<p>Mattia sings the italian nursery rhyme about the grasshopper and the ant.</p>'},
    {data: '<p>Making love</p>'},
    {data: '<p>Making love</p>'},
    {data: '<p>Making love</p>'},
    {data: '<p>Cat cries for no apparent reason and Mattia stays the night to comfort her.</p>'},
    {data: '<p>June 9th: "Do you want to make out in your car?"</p>'},
    {data: '<p>June 9th: Mattia made a reservation at The Forge for vegan tapas. They were amazing. They give each other tarot card readings.</p>'},
    {data: '<p>June 9th: Mattia made a reservation at The Forge for vegan tapas. They were amazing.</p>'},
    {data: '<p>June 7th: Mattia sends Cat a meme: "Do you want to Gnome better?".<br>Cat sends Mattia a meme: "What if we kissed? Bottom Text."</p>'},
    {data: '<p>June 24th: Cat is already missing Mattia as she codes this.</p>'},
    {data: '<p>I didn\'t expect to feel this way.</p>'},
    {data: '<p>I didn\'t expect to feel this way.</p>'},
    {data: '<p>June 14th: Mattia reads the poem Milos by Anis Mojgani in the kitchen of the AirBnb: <br>"we are apples, our love is an arrow. I am unbuttoning my shirt painting a circle over my heart<br>you<br>shoot straight"</p>'},
    {data: '<p>June 29th: Putting our feet into the creek at Rock Falls Park. Mattia asks Cat: "Are you my girlfriend?" </p>'},
    {data: '<p>June 29th: Mattia suddenly arrives at Cat\'s AirBnb with breakfast. He skipped the work to spend the day with her.</p>'},
    {data: '<p>June 29th: Cat meets Mattia\'s mom and she tries to feed Cat. She gives Cat cold tea and they talk about the weather.</p>'},
    {data: '<p>June 9th: Cat is very nervous as she is getting ready for their first date. Her heart is beating so hard walking up to the restaurant.</p>'},
    {data: '<p>June 26th: Mattia refuses to kill the spider in Cat\'s AirBnb, because he is a gentle person.</p>'},
    {data: '<p>June 25th: Cat got an offer to be a full time professor, so Mattia takes Cat to dinner. It feels bittersweet.</p>'},
    {data: '<p>June 26th: Drag show and dancing at Spirit. Cat and Mattia sing "Career Boy" by Dorian Electra in the car.</p>'},
    {data: '<p>June 27th: Cat and Mattia finish the blinking videogame "Before Your Eyes" and Mattia cries at the ending. It\'s a very sad ending :(</p>'},
    {data: '<p>June 26th: Mattia is officially obsessed with Spak Bros\' calzones and seitan</p>'},
    {data: '<p>Mattia tells Cat about the friends that mistreated him and she feels so angry that people would mistreat this kind and gentle person.</p>'},
    {data: '<p>Cat tells Mattia about the coworkers and ex-boyfriends that mistreated her and he gets so angry that people would mistreat her like that.</p>'},
    {data: '<p>June 12th: Walking through the Andy Warhol museum, finding a piece ("What Horses") by Chole Wise with two televisions broadcasting very awkward conversations: "I am a very stable genius. Trust me"</p>'},
    {data: '<p>June 16th: Mattia makes Cat chickpea balls, and they\'re wonderful.</p>'},
    {data: '<p>June 15th: Mattia and Cat play Mario Kart and Return of the Obra Dinn.</p>'},
    {data: '<p>June 15th: Cat reads "Over the Anvil we Stretch by Anis Mojgani:"<br>"it felt like the night was closing in on us<br>we did the only thing that two people with soft hearts <br>can do on the last day of it all<br>the bed creaked like the stars outside<br>they shot themselves at the earth <br>trying to get here faster"</p>'},
    {data: '<p>June 13th: Mattia whispers poetry in Cat\'s ear after they make love. I wish he kept doing that</p>'},
    {data: '<p>Mattia randomly speaks Italian to Cat. It\'s always something cute</p>'},
    {data: '<p>June 28th: Mattia begins to sing Hope to Die by Orville Peck because he is sad Cat is leaving :(</p>'},
    {data: '<p>June 27th: Cat and Mattia are saying goodbye at the front door. Mattia kisses Cat, tries to leave, comes back to kiss Cat again, tries to leave, comes back to kiss Cat again...</p>'},
    {data: '<p>June 27th: Mattia mentions maybe he could move to Austin. Cat wants him to make sure he can be happy and inspired. They agree he should visit first and see how it goes. Is that crazy?</p>'},
    {data: '<p>June 30th: Cat is leaving today. Cat and Mattia are saying goodbye at the front door. Mattia kisses Cat, tries to leave, comes back to kiss Cat again, tries to leave, comes back to kiss Cat again...</p>'},
    {data: '<p>June 30th: Cat is leaving today. Mattia keeps delaying his alarm to stay in Cat\'s arms. Cat holds back tears</p>'},
    {data: '<p>June 30th: Cat is driving to Illinois and can no longer hold back her tears</p>'},
    {data: '<p>June 18th: Cat ditches weird friends to dance with Mattia at Spirit.</p>'},
    {data: '<p>June 19th: More kisses with a view of Pittsburgh, good conversation, and disappointing Onion Maiden. The "Liquid Death" is good tho.</p>'},
  ]
}
var lastThought = "<p>july 1st: It\'s only been 25 days since I started falling in love with you. Whatever happens between us, you are precious and I care about you. - Cat</p>"
