var wikipedia = {
  paragraphs: [
    {data: '<p><i><b>Physarum polycephalum</b></i>, an <a href="https://en.wikipedia.org/wiki/Acellular" class="mw-redirect" title="Acellular">acellular</a> <a href="https://en.wikipedia.org/wiki/Slime_mold" title="Slime mold">slime mold</a> or <a href="https://en.wikipedia.org/wiki/Myxomycete" class="mw-redirect" title="Myxomycete">myxomycete</a>, is a <a href="https://en.wikipedia.org/wiki/Protist" title="Protist">protist</a> with diverse cellular forms and broad geographic distribution.  The “acellular” moniker derives from the plasmodial stage of the <a href="https://en.wikipedia.org/wiki/Biological_life_cycle" title="Biological life cycle">life cycle</a>:  the <a href="https://en.wikipedia.org/wiki/Plasmodium_(life_cycle)" title="Plasmodium (life cycle)">plasmodium</a> is a bright yellow macroscopic <a href="https://en.wikipedia.org/wiki/Multinucleate" title="Multinucleate">multinucleate</a> <a href="https://en.wikipedia.org/wiki/Coenocyte" title="Coenocyte">coenocyte</a> shaped in a network of interlaced tubes.  This stage of the life cycle, along with its preference for damp shady habitats, likely contributed to the original mischaracterization of the organism as a <a href="https://en.wikipedia.org/wiki/Fungus" title="Fungus">fungus</a>. <i>P. polycephalum</i> is used as a model organism for research into motility, cellular differentiation, chemotaxis, cellular compatibility, and the cell cycle.</p>'
    },
    {data: '<p><i>Physarum polycephalum</i> has been shown to exhibit characteristics similar to those seen in single-celled creatures and <a href="https://en.wikipedia.org/wiki/Eusocial" class="mw-redirect" title="Eusocial">eusocial</a> insects. For example, a team of Japanese and Hungarian researchers have shown <i>P.&#160;polycephalum</i> can solve the <a href="https://en.wikipedia.org/wiki/Shortest_path_problem" title="Shortest path problem">shortest path problem</a>. When grown in a maze with oatmeal at two spots, <i>P.&#160;polycephalum</i> retracts from everywhere in the maze, except the shortest route connecting the two food sources.</p>'
    },
    {data: '<p>When presented with more than two food sources, <i>P.&#160;polycephalum</i> apparently solves a more complicated <a href="https://en.wikipedia.org/wiki/Transportation_problem" class="mw-redirect" title="Transportation problem">transportation problem</a>. With more than two sources, the amoeba also produces efficient networks.<i>P.&#160;polycephalum</i> created a network similar to the existing train system, and "with comparable efficiency, fault tolerance, and cost". Similar results have been shown based on road networks in the <a href="https://en.wikipedia.org/wiki/United_Kingdom" title="United Kingdom">United Kingdom</a> and the <a href="https://en.wikipedia.org/wiki/Iberian_peninsula" class="mw-redirect" title="Iberian peninsula">Iberian peninsula</a> (i.e., <a href="https://en.wikipedia.org/wiki/Spain" title="Spain">Spain</a> and <a href="https://en.wikipedia.org/wiki/Portugal" title="Portugal">Portugal</a>).<i>P.&#160;polycephalum</i> not only can solve these computational problems but also exhibits some form of memory. By repeatedly making the test environment of a specimen of <i>P.&#160;polycephalum</i> cold and dry for 60&#160;minute intervals, <a href="https://en.wikipedia.org/wiki/Hokkaido_University" title="Hokkaido University">Hokkaido University</a> biophysicists discovered that the slime mold appears to anticipate the pattern by reacting to the conditions when they did not repeat the conditions for the next interval. Upon repeating the conditions, it would react to expect the 60&#160;minute intervals, as well as testing with 30 and 90&#160;minute intervals.</p>'
    },
    {data: '<p><i>P.&#160;polycephalum</i> has also been shown to dynamically re-allocate to apparently maintain constant levels of different nutrients simultaneously.In one particular instance, a specimen placed at the center of a <a href="https://en.wikipedia.org/wiki/Petri_dish" title="Petri dish">Petri dish</a> spatially re-allocated over combinations of food sources that each had different <a href="https://en.wikipedia.org/wiki/Protein" title="Protein">protein</a>-<a href="https://en.wikipedia.org/wiki/Carbohydrate" title="Carbohydrate">carbohydrate</a> ratios. After 60&#160;hours, the slime mold area over each food source was measured. For each specimen, the results were consistent with the hypothesis that the amoeba would balance total protein and carbohydrate intake to reach particular levels that were invariant to the actual ratios presented to the slime mold.</p>'
    },
    {data: '<p>As the slime mold does not have any nervous system that could explain these intelligent behaviours, there has been considerable interdisciplinary interest in understanding the rules that govern its behaviour. Scientists are trying to model the slime mold using a number of simple, distributed rules. For example, <i>P.&#160;polycephalum</i> has been modeled as a set of <a href="https://en.wikipedia.org/wiki/Differential_equation" title="Differential equation">differential equations</a> inspired by electrical networks. This model can be shown to be able to compute shortest paths. A very similar model can be shown to solve the <a href="https://en.wikipedia.org/wiki/Steiner_tree_problem" title="Steiner tree problem">Steiner tree problem</a>. However, currently these models do not make sense biologically, as they for example assume energy conservation inside the slime mold. To build more realistic models, more data about the slime mold\'s network construction needs to be gathered. To this end, researchers are analysing the network structure of lab-grown <i>P.&#160;polycephalum</i>.</p>'
    },
    {data: '<p>In a book and several preprints that have not been scientifically peer reviewed, it has been claimed that because plasmodia appear to react in a consistent way to stimuli, they are the "ideal substrate for future and emerging <a href="https://en.wikipedia.org/wiki/Biologically-inspired_computing" class="mw-redirect" title="Biologically-inspired computing">bio-computing devices</a>". An outline has been presented showing how it may be possible to precisely point, steer and cleave plasmodium using light and food sources, especially <a href="https://en.wikipedia.org/wiki/Valerian_(herb)#Effect_on_other_organisms" title="Valerian (herb)">Valerian root</a>. Moreover, it has been reported that plasmodia can be made to form <a href="https://en.wikipedia.org/wiki/Logic_gate" title="Logic gate">logic gates</a>, enabling the construction of biological computers. In particular, plasmodia placed at entrances to special geometrically shaped mazes would emerge at exits of the maze that were consistent with <a href="https://en.wikipedia.org/wiki/Truth_table" title="Truth table">truth tables</a> for certain primitive logic connectives. However, as these constructions are based on theoretical models of the slime mold, in practice these results do not scale to allow for actual computation. When the primitive logic gates are connected to form more complex functions, the plasmodium ceased to produce results consistent with the expected truth tables.</p>'
    },
    {data: '<p>Even though complex computations using <i>Physarum</i> as a substrate are currently not possible, researchers have successfully used the organism\'s reaction to its environment in a USB sensor and to control a robot.</p>'
    },
    {data: '<p><a href="https://en.wikipedia.org/wiki/File:Physarum_polycephalum_plasmodium.jpg" class="image"><img alt="Physarum polycephalum plasmodium.jpg" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Physarum_polycephalum_plasmodium.jpg/220px-Physarum_polycephalum_plasmodium.jpg" decoding="async" width="220" height="165" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Physarum_polycephalum_plasmodium.jpg/330px-Physarum_polycephalum_plasmodium.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Physarum_polycephalum_plasmodium.jpg/440px-Physarum_polycephalum_plasmodium.jpg 2x" data-file-width="1024" data-file-height="768" /></a></br><i>P. polycephalum</i> plasmodium on tree bark</p>'},
    {data: '<p><a href="https://en.wikipedia.org/wiki/File:1n%2B2nLC.gif" class="image"><img alt="The life cycle of Physarum polycephalum. The outer circuit illustrates the natural cycle alternating between the haploid amoebal stage and diploid plasmodial stage. The inner circuit illustrates the fully haploid &quot;apogamic&quot; life cycle. Both cycles exhibit all developmental stages." src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/1n%2B2nLC.gif/220px-1n%2B2nLC.gif" decoding="async" width="220" height="300" class="thumbimage" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/8e/1n%2B2nLC.gif/330px-1n%2B2nLC.gif 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/8e/1n%2B2nLC.gif/440px-1n%2B2nLC.gif 2x" data-file-width="2125" data-file-height="2900" /></a></br>The life cycle of <i>Physarum polycephalum</i>.  The outer circuit illustrates the natural cycle alternating between the haploid amoebal stage and diploid plasmodial stage.  The inner circuit illustrates the fully haploid "apogamic" life cycle.  Both cycles exhibit all developmental stages.</p>'},
    {data: '<a href="https://en.wikipedia.org/wiki/File:Physarum_polycephalum_amoebae.jpg" class="image"><img alt="P. polycephalum amoebae growing on lawns of live E. coli. The bacterial cells are approx 1 micron in diameter, amoebae are approx 10 microns in diameter. Bright circular structures inside the amoebae are vacuoles, nuclei are pale grey circles each containing a darker nucleolus. (Phase contrast microscopy.)" src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Physarum_polycephalum_amoebae.jpg/220px-Physarum_polycephalum_amoebae.jpg" decoding="async" width="220" height="162" class="thumbimage" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/08/Physarum_polycephalum_amoebae.jpg/330px-Physarum_polycephalum_amoebae.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/08/Physarum_polycephalum_amoebae.jpg/440px-Physarum_polycephalum_amoebae.jpg 2x" data-file-width="2630" data-file-height="1933" /></a></br><i>P. polycephalum</i> amoebae growing on lawns of live <i>E. coli.</i> The bacterial cells are approx 1 micron in diameter, amoebae are approx 10 microns in diameter. Bright circular structures inside the amoebae are vacuoles, nuclei are pale grey circles each containing a darker nucleolus. (Phase contrast microscopy.)'}
  ]
}
